-----------------------------------------------------------
-- Import Lua modules
-----------------------------------------------------------
require("settings")
require("keymaps")
require("plugins")
require("colorscheme")
require("plugins.cmp")
require("plugins.lsp")
require("plugins.autopairs")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.comment")
require("plugins.gitsigns")
require("plugins.nvim-tree")
require("plugins.bufferline")
require("plugins.lualine")
require("plugins.toggleterm")
require("plugins.project")
require("plugins.impatient")
require("plugins.alpha")
require("plugins.whichkey")
require("plugins.autocommands")
require("plugins.indentline")

require("neoscroll").setup()
